### ISSUE TITLE
Broken with Chef 13

### ISSUE THREAD

**Issue by barrowkwan** [gocd/go-cookbook#113]
with this error

Property `resources` of resource `gocd_agent` overwrites an existing method.

**Comment by varshavaradarajan** [comment]
```
Deprecated features used!
  Property `retries` of resource `java_ark` overwrites an existing method. Please use a different property name. This will raise an exception in Chef 13. at 1 location:
    - /var/chef/cache/cookbooks/java/resources/ark.rb:46:in `class_from_file'
   See https://docs.chef.io/deprecations_property_name_collision.html for further details.
  Property `retry_delay` of resource `java_ark` overwrites an existing method. Please use a different property name. This will raise an exception in Chef 13. at 1 location:
    - /var/chef/cache/cookbooks/java/resources/ark.rb:47:in `class_from_file'
   See https://docs.chef.io/deprecations_property_name_collision.html for further details.
  Property `resources` of resource `gocd_agent` overwrites an existing method. Please use a different property name. This will raise an exception in Chef 13. at 1 location:
    - /var/chef/cache/cookbooks/gocd/resources/agent.rb:17:in `class_from_file'
   See https://docs.chef.io/deprecations_property_name_collision.html for further details.
  Property `resources` of resource `gocd_agent_autoregister_file` overwrites an existing method. Please use a different property name. This will raise an exception in Chef 13
```

Cannot support Chef 13 until the dependent cookbooks also make the change (in our case java, and their [latest](https://supermarket.chef.io/cookbooks/java#changelog) doesn't mention it). I'll keep an eye out for their update and make the change. Meanwhile , I'll add a deprecation notice for our custom resources making use of the reserved property names and tell users that we are going to rename them. Sound ok?

**Comment by barrowkwan** [comment]
sounds good.  thanks!
